version: '2'
services:
  jhipstercouchdbsample-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      - TYPE=MASTER
      - BUCKET=jhipsterCouchDBSample
  jhipstercouchdbsample-couchbase-node:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    environment:
      - TYPE=WORKER
      - BUCKET=jhipsterCouchDBSample
      - COUCHBASE_MASTER=jhipstercouchdbsample-couchbase
      - AUTO_REBALANCE=false
